dist: trusty
sudo: required
language: generic

services:
  - docker

env:
  - TEST_SUITE=./spec/build_spec.cr
  - TEST_SUITE=./spec/amber

script:
  - docker-compose run spec bash -c "bin/ameba"
  - docker-compose run spec bash -c "crystal spec $TEST_SUITE -D run_build_tests"

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/aaf02221d4649d70b384
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always

